### ISSUE TITLE
dist/index.d.ts missing from distribution

### ISSUE THREAD

**Issue by mjpieters** [Sub-Xaero/stimulus-library#105]
Your package.json states you include typescript types:

```
  "types": "dist/index.d.ts",
```

but, there is no `index.d.ts` in the `dist` folder. This means I can't import individual controllers in my typescript project, because typescript won't resolve imports for this library.

For some reason, you disabled declarations in 3b374f62bf4c59501841461319287607246cdb5a, can you please set `declarations` in tsconfig.json back to true?

**Comment by Sub-Xaero** [comment]
Thanks @mjpieters, not sure how that slipped through 🙈 

Fixed in 1f877b3ee86493f44f030a2aa502e54f055dae75 and just cut a new release 0.9.9 that exports the proper type definitions. Let me know if that fixes it for you.

**Comment by mjpieters** [comment]
This indeed fixes this issue, thanks!
