### ISSUE TITLE
How to install when only using a mixin (w/ tree shaking)?

### ISSUE THREAD

**Issue by drewlustro** [Sub-Xaero/stimulus-library#106]
The installation instructions prescribe `yarn install` `npm install`, but that did not work in my project because I use import maps.

I then ran the following:

```sh
bin/importmap pin stimulus-library
```

Which pinned a **ton** of dependencies:

```sh
Pinning "stimulus-library" to https://ga.jspm.io/npm:stimulus-library@0.9.11/dist/index.js
Pinning "@hotwired/stimulus" to https://ga.jspm.io/npm:@hotwired/stimulus@3.2.1/dist/stimulus.js
Pinning "date-fns/formatDistanceToNow" to https://ga.jspm.io/npm:date-fns@2.29.3/esm/formatDistanceToNow/index.js
Pinning "date-fns/formatDuration" to https://ga.jspm.io/npm:date-fns@2.29.3/esm/formatDuration/index.js
Pinning "date-fns/intervalToDuration" to https://ga.jspm.io/npm:date-fns@2.29.3/esm/intervalToDuration/index.js
Pinning "date-fns/isPast" to https://ga.jspm.io/npm:date-fns@2.29.3/esm/isPast/index.js
Pinning "date-fns/toDate" to https://ga.jspm.io/npm:date-fns@2.29.3/esm/toDate/index.js
Pinning "dialog-polyfill" to https://ga.jspm.io/npm:dialog-polyfill@0.5.6/dist/dialog-polyfill.js
Pinning "lodash-es/camelCase" to https://ga.jspm.io/npm:lodash-es@4.17.21/camelCase.js
Pinning "lodash-es/clamp" to https://ga.jspm.io/npm:lodash-es@4.17.21/clamp.js
Pinning "lodash-es/debounce" to https://ga.jspm.io/npm:lodash-es@4.17.21/debounce.js
Pinning "lodash-es/get" to https://ga.jspm.io/npm:lodash-es@4.17.21/get.js
Pinning "lodash-es/set" to https://ga.jspm.io/npm:lodash-es@4.17.21/set.js
Pinning "lodash-es/upperFirst" to https://ga.jspm.io/npm:lodash-es@4.17.21/upperFirst.js
Pinning "mitt" to https://ga.jspm.io/npm:mitt@3.0.0/dist/mitt.mjs
Pinning "smoothscroll-polyfill" to https://ga.jspm.io/npm:smoothscroll-polyfill@0.4.4/dist/smoothscroll.js
```

Will all these dependencies ship with my bundle?

I'm only interested in `useLocalStorage` for now.

**Comment by Sub-Xaero** [comment]
Hey @drewlustro , 

Interesting! I mostly have designed the library to work with bundler setups like esbuild, rollup and webpack, which are able to tree-shake those dependencies if they're not used, but I've had a couple of users who have struggled with import maps so I'll try to pay attention to this problem. 

I've also wondered for a while about creating some smaller packages for users like yourself that just want the mixins and not the controllers, so I might release a `stimulus-library/mixins` package to make that easier. 

Leave it with me, hopefully I'll get around to doing that some time soon. 

In the meanwhile, feel free to just copy the mixins you need into your own code if that's straight forward for you. I'm very happy for people to do that.

**Comment by Sub-Xaero** [comment]
Hey @drewlustro 

Just published an npm package with just the mixins, https://www.npmjs.com/package/@stimulus-library/mixins and minimal dependencies. 

Let me know if that works for you. Closing this issue for now, feel free to reopen if there are still issues.

**Comment by drewlustro** [comment]
@Sub-Xaero – This worked fantastically! Thank you for the quick turnaround 💪

**Comment by Sub-Xaero** [comment]
@drewlustro my pleasure, Happy hacking!
