### ISSUE TITLE
DisableWithController prevents form sumitting

### ISSUE THREAD

**Issue by jer0m** [Sub-Xaero/stimulus-library#177]
Hello,
First, thank you for this useful set of controllers!

I have a problem with the DisableWithController, when I use it in a rails form, the form is not submitted anymore.

Stimulus-library 1.0.2
Rails 6.1.7.6

Here is the form:
```
<%= form_with url: sessions_path do |form| %>
<%= text_field_tag 'email' %>
<%= password_field_tag 'password' %>
<%= form.submit 'Sign in', data: { controller: "disable-with", 'disable-with-message-value': "Bear with us..." } %>
<% end %>
```

When I click the button is disabled with the good text but the form is not submitted. If I remove the controller, the form is submitted.
It does not work no matter if turbo is enabled or not.

What I'm doing wrong?

Thanks

**Comment by jer0m** [comment]
Nvm I now use the builtin mechanism in Turbo. Sorry for the noise.

**Comment by Sub-Xaero** [comment]
@jer0m Thanks for reporting! 

I'll definitely look into it, but equally I first wrote this controller when `@hotwired/turbo` was in alpha and didn't support a lot of the old UJS methods like `data-method`, `data-confirm` , and `data-disable-with`, so I might just deprecate this controller and encourage people to use the Turbo or [Mrujs](https://github.com/KonnorRogers/mrujs) `disable-with` functionality instead.
