### ISSUE TITLE
Does not run under node.js

### ISSUE THREAD

**Issue by gap777** [Sub-Xaero/stimulus-library#178]
We're using this package in a Rails 7 app, and have JS unit tests (running under node) against some of our stimulus controllers. In this configuration, we are unable to load components from this package. 

Would you be willing to define the `main` attribute in your package.json files (controllers, mixins,  utilities) to enable this configuration? See https://esbuild.github.io/api/#main-fields

Thank you!

**Comment by Sub-Xaero** [comment]
Of course! I've cut a new release (v1.0.3) for you now, with that in. 

Let me know if there's anything else I can do to help. 

Closed in d465934590add1321fafd261ed9c920f971522a1

**Comment by gap777** [comment]
@Sub-Xaero That fixed it! Thank you!
