### ISSUE TITLE
Letting auto-submit-form see external inputs

### ISSUE THREAD

**Issue by gior** [Sub-Xaero/stimulus-library#329]
As of v1.0.7, `auto-submit-form` only takes into account inputs inside the form.

HTML allows to define inputs outside the form, using the `form="<form_id>"` attribute. I find it very useful in complex layouts.

In order to profit from autosubmission, `get inputElements()` in `AutoSubmitFormController` could add to the list of inputs all input elements in the document with the `form="<form_id>"` attribute 

I'd like to submit this small PR myself, but I'm totally out of date re TypeScript dev tooling, and quite busy at the moment.
Thanks to anybody able to add the feature faster than me.

**Comment by Sub-Xaero** [comment]
Thanks for raising this @gior , that's a great idea! 

This will be added by #330 and I'll cut a new release for it within the hour.
