### ISSUE TITLE
CountdownController to show readable time

### ISSUE THREAD

**Issue by kwhandy** [Sub-Xaero/stimulus-library#345]
Current view for time display of countdown_controller's time in _minute:second_ format is `2:9` instead showing `02:09`, I wonder is this a bug or any reason behind this?

**Comment by Sub-Xaero** [comment]
Hello @kwhandy ,

That's entirely on me, I wrote the Countdown controller according to my own use-case at the time which was to show the countdown in words, like I display in the examples:
![Screenshot 2024-04-17 at 16 08 08](https://github.com/Sub-Xaero/stimulus-library/assets/9960703/31743991-28d6-48fe-8cad-737643f0ab9b)

But zero-padded is a very valid use-case too, so I've added this functionality behind a config flag in #351. If you set `data-countdown-pad-zeros-value="true"` on your element, it will now have the desired effect:

![Screenshot 2024-04-17 at 16 35 56](https://github.com/Sub-Xaero/stimulus-library/assets/9960703/75ccb907-afbb-458f-97d3-95df5158474d)

I'll cut a new release for this shortly.

**Comment by kwhandy** [comment]
whoa! tysm, appreciate the response:))
