### ISSUE TITLE
Wrong dependency?

### ISSUE THREAD

**Issue by pySilver** [Sub-Xaero/stimulus-library#72]
Shouldn't this library be dependant of `@hotwired/stimulus` instead of `stimulus` ?
https://github.com/Sub-Xaero/stimulus-library/blob/477ed1e0a9789d4f9611ebc243b61ce9442b4348/package.json#L62

**Comment by pySilver** [comment]
Hello @Sub-Xaero ,

Honestly I'm not sure what would be the proper workaround. At the moment once installed `stimulus-library` I'm not able to build my app without explicitly installing `stimulus` package. Build script fails with the following error:

```
ERROR in ./node_modules/stimulus-library/dist/stimulus-library.es.js 21:0-38
Module not found: Error: Can't resolve 'stimulus' in '/Users/Silver/Projects/xxxxxxx-ui/node_modules/stimulus-library/dist'

webpack compiled with 1 error
```

Obviously, to make it work, I should add the dependency into my project too.

**Comment by Sub-Xaero** [comment]
Yeah that's not great. Sorry about that!

I've just released 0.7.5, which removes `stimulus` as a peerDependency, let me know if that fixes the issue for you @pySilver

**Comment by Sub-Xaero** [comment]
Damn. 
Looks like something in the build system is broken, #76  never used to be a problem either.

I'm going back to basics, simplifying the build system and only supporting ESModules, If you want to add `"stimulus-library": "0.8.0-beta"` to your `package.json` and let me know if that fixes this for you?

**Comment by pySilver** [comment]
Works fine that way!
