### ISSUE TITLE
any example or controller for modal and slideovers?

### ISSUE THREAD

**Issue by laptopmutia** [Sub-Xaero/stimulus-library#80]
slideovers like this one?
https://codepen.io/devdojo/pen/NWyPrGe

regardless 
I really like your library its really clean thanks for this repo

**Comment by Sub-Xaero** [comment]
@laptopmutia 
Hiya, I don't have any specific slideover controllers, but you could potentially achieve it quite easily with a generic controller like https://sub-xaero.github.io/stimulus-library/docs/controllers/general/ToggleClassController. 

Generally with behaviours like that, I'd expect to be able to just toggle an `active` class or something similar that will trigger the change in styles that make the slideover appear. With tailwind, you might either need to extract a custom class that `@apply`s all the utility classes, and an `.active` class that can be toggled on and off. Or copy the code of the `ToggleClassController` to make it work for your specific use case, toggling multiple classes on multiple targets.

**Comment by Sub-Xaero** [comment]
@laptopmutia  Haven't heard back, so I'm closing this issue for the time being. 
Please feel free to re-open the issue if you want to request a specific controller to be added to the library.
