### ISSUE TITLE
Signal visibilty issue: Uncaught Error: Could not find operator in expression

### ISSUE THREAD

**Issue by szluyufeng** [Sub-Xaero/stimulus-library#96]
This controller didn't work, and didn't work on  "[official demo controller](https://sub-xaero.github.io/stimulus-library/docs/controllers/signal/SignalVisibilityController)" also.

**Comment by Sub-Xaero** [comment]
@szluyufeng  Thanks for reporting. Closed by 9bc878c80bee51d195db701e0bba99ed6322941e

I've just cut a new release 0.9.3, with the fix for this issue. Let me know if you're still having troubles in the new version.

**Comment by szluyufeng** [comment]
Excellent. Thanks for your effort!
